In [1]:
print("Hello I'm  excited to learn Pytorch")

Hello I'm  excited to learn Pytorch


In [2]:
!nvidia-smi


/bin/bash: /usr/bin/nvidia-smi: Permission denied


In [9]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.5.0+cu101


## Introduction to Tensors


### Creating tonsors 

In [7]:
# scalar
scalar = torch.tensor(7)
scalar.item()

7

In [8]:
scalar.ndim

0

In [9]:
# Get tensor back as Python int 
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [8,7]])
MATRIX

tensor([[7, 8],
        [8, 7]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[1]

tensor([8, 7])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,8]]])
TENSOR                        

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [21]:
TENSOR.ndim

3

### Random TENSOR
Random tensors are important  beecause  the way many neural networks learn is that 
they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers  ==>  look at data ==> update ramdom numbers ==> look at data ==> update random numbers

In [3]:
# Createa random  tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4199, 0.2227, 0.7271, 0.8371],
        [0.2827, 0.2268, 0.7910, 0.9900],
        [0.0398, 0.7669, 0.4165, 0.1964]])

In [4]:
random_tensor.ndim 

2

In [8]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor_size =  torch.rand(size=(224,224,3)) # height, width, colour channel
random_image_tensor_size.shape, random_image_tensor_size.ndim

(torch.Size([224, 224, 3]), 3)

In [10]:
torch.rand(size=(3,2))

tensor([[0.7818, 0.2227],
        [0.9635, 0.8520],
        [0.8942, 0.1053]])

### Zeros and ones

In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [18]:
# Use torch range()
one_to_ten = torch.arange(start = 0,end =10, step=3) ## range co the bi loai bo
one_to_ten

tensor([0, 3, 6, 9])

In [19]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0])

### Tensor datatypes

** Note: ** Tensor datatypes is one of the 3 big issues whose you'll run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0]
                               ,dtype=None, # What datatype is the tensor (e.g float32, float16)
                               device=None, # What device is yours tensor on 
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16) # Convert data 32bit to 16bit 
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
test = float_32_tensor * float_16_tensor
test.dtype

torch.float32

### Getting information from tensors
1. Tensors not right datatype - to do get datatype from a tensor,  can use `tensor.dtype`
2. Tensors not right shape - to do get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to do get device from a tensor, `tensor.device`

In [30]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9586, 0.5280, 0.5484, 0.4929],
        [0.2203, 0.8921, 0.9236, 0.3008],
        [0.4819, 0.7651, 0.6333, 0.3439]])

In [32]:
# Find out details about some tensors (tensor attributes)
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor on : {some_tensor.device}')

tensor([[0.9586, 0.5280, 0.5484, 0.4929],
        [0.2203, 0.8921, 0.9236, 0.3008],
        [0.4819, 0.7651, 0.6333, 0.3439]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor on : cpu
